spring.application.name=demo_basic

spring.config.import=optional:file:.env[.properties]

# PostgreSQL Database Configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# Cambia el nivel global a solo Advertencias y Errores
logging.level.root=WARN

# ==========================================
# Configuración de OpenAPI / Swagger UI
# ==========================================
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.operations-sorter=alpha

# Enable/disable the Scalar API reference (default: false)
scalar.enabled=true
# The URL of your OpenAPI document
# scalar.url=http://localhost:8080/api-docs
scalar.url=https://pi-deploy-ouni.onrender.com/api-docs

# JWT Configuration
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000


